version 0.15.0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -39,6 +39,17 @@ if [ "$ARROW_R_DEV" == "TRUE" ]; then
   ${R_HOME}/bin/Rscript data-raw/codegen.R
 fi
 
+if [ "$LOCAL_AUTOBREW" == "TRUE" ]; then
+  # LOCAL_AUTOBREW means use the script in tools/
+  # If you want to use a local apache-arrow.rb formula, do:
+  # $ cp ../dev/tasks/homebrew-formulae/autobrew/apache-arrow.rb tools/apache-arrow.rb
+  # before R CMD build (assuming a local checkout of the apache/arrow repository)
+  # FORCE_AUTOBREW without LOCAL_AUTOBREW means to pull from jeroen.github.io
+  cp tools/autobrew .
+  cp tools/apache-arrow.rb .
+  FORCE_AUTOBREW="TRUE"
+fi
+
 # Note that cflags may be empty in case of success
 if [ "$INCLUDE_DIR" ] || [ "$LIB_DIR" ]; then
   echo "Found INCLUDE_DIR and/or LIB_DIR!"
@@ -47,7 +58,7 @@ if [ "$INCLUDE_DIR" ] || [ "$LIB_DIR" ]; then
 else
   # Use pkg-config if available
   pkg-config --version >/dev/null 2>&1
-  if [ $? -eq 0 ]; then
+  if [ "$FORCE_AUTOBREW" != "TRUE" ] && [ $? -eq 0 ]; then
     PKGCONFIG_CFLAGS=`pkg-config --cflags --silence-errors ${PKG_CONFIG_NAME}`
     PKGCONFIG_LIBS=`pkg-config --libs --silence-errors ${PKG_CONFIG_NAME}`
   fi
@@ -58,14 +69,18 @@ else
     PKG_LIBS=${PKGCONFIG_LIBS}
   else
     if [[ "$OSTYPE" == "darwin"* ]]; then
-      if [ "$(command -v brew)" ] && [ "$(brew ls --versions ${PKG_BREW_NAME})" != "" ]; then
+      if [ "$FORCE_AUTOBREW" != "TRUE" ] && [ "$(command -v brew)" ] && [ "$(brew ls --versions ${PKG_BREW_NAME})" != "" ]; then
         echo "Using Homebrew ${PKG_BREW_NAME}"
         BREWDIR=$(brew --prefix)
       else
         echo "Downloading ${PKG_BREW_NAME}"
-        curl -sfL "https://jeroen.github.io/autobrew/$PKG_BREW_NAME" > autobrew
-        if [ $? -ne 0 ]; then
-          echo "Failed to download manifest for ${PKG_BREW_NAME}"
+        if [ -f "autobrew" ]; then
+          echo "Using local manifest for ${PKG_BREW_NAME}"
+        else
+          curl -sfL "https://jeroen.github.io/autobrew/$PKG_BREW_NAME" > autobrew
+          if [ $? -ne 0 ]; then
+            echo "Failed to download manifest for ${PKG_BREW_NAME}"
+          fi
         fi
         source autobrew
         if [ $? -ne 0 ]; then
@@ -79,14 +94,14 @@ else
 fi
 
 # Find compiler
-CXXCPP=$("${R_HOME}"/bin/R CMD config CXXCPP)
+CXXCPP="$(${R_HOME}/bin/R CMD config CXX11) -E"
 CXX11FLAGS=$("${R_HOME}"/bin/R CMD config CXX11FLAGS)
 CXX11STD=$("${R_HOME}"/bin/R CMD config CXX11STD)
 CPPFLAGS=$("${R_HOME}"/bin/R CMD config CPPFLAGS)
 
 # If libarrow uses the old GLIBCXX ABI, so we have to use it too
 if [ "$ARROW_USE_OLD_CXXABI" ]; then
-  $PKG_CFLAGS="$PKG_CFLAGS -D_GLIBCXX_USE_CXX11_ABI=0"
+  PKG_CFLAGS="$PKG_CFLAGS -D_GLIBCXX_USE_CXX11_ABI=0"
 fi
 
 # Test configuration
@@ -110,6 +125,11 @@ else
   echo "---------------------------------------------------------"
   PKG_LIBS=""
   PKG_CFLAGS=""
+fi
+
+# Set any user-defined CXXFLAGS
+if [ "$ARROW_R_CXXFLAGS" ]; then
+  PKG_CFLAGS="$PKG_CFLAGS $ARROW_R_CXXFLAGS"
 fi
 
 # Write to Makevars
