version 1.0.0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -36,7 +36,6 @@ PKG_LIBS="-larrow_dataset -lparquet -larrow"
 
 # Make some env vars case-insensitive
 ARROW_R_DEV=`echo $ARROW_R_DEV | tr '[:upper:]' '[:lower:]'`
-LOCAL_AUTOBREW=`echo $LOCAL_AUTOBREW | tr '[:upper:]' '[:lower:]'`
 FORCE_AUTOBREW=`echo $FORCE_AUTOBREW | tr '[:upper:]' '[:lower:]'`
 ARROW_USE_PKG_CONFIG=`echo $ARROW_USE_PKG_CONFIG | tr '[:upper:]' '[:lower:]'`
 
@@ -49,15 +48,20 @@ if [ "$ARROW_R_DEV" = "true" ]; then
   ${R_HOME}/bin/Rscript data-raw/codegen.R
 fi
 
-if [ "$LOCAL_AUTOBREW" = "true" ]; then
-  # LOCAL_AUTOBREW means use the script in tools/
-  # If you want to use a local apache-arrow.rb formula, do:
+if [ -f "tools/apache-arrow.rb" ]; then
+  # If you want to use a local apache-arrow.rb formula, do
   # $ cp ../dev/tasks/homebrew-formulae/autobrew/apache-arrow.rb tools/apache-arrow.rb
-  # before R CMD build (assuming a local checkout of the apache/arrow repository)
-  # FORCE_AUTOBREW without LOCAL_AUTOBREW means to pull from jeroen.github.io
+  # before R CMD build or INSTALL (assuming a local checkout of the apache/arrow repository)
   cp tools/autobrew .
-  cp tools/apache-arrow.rb .
-  FORCE_AUTOBREW="true"
+  if [ "$FORCE_AUTOBREW" != "false" ]; then
+    # It is possible to turn off forced autobrew if the formula is included,
+    # but most likely you shouldn't because the included formula will reference
+    # the C++ library at the version that matches the R package.
+    FORCE_AUTOBREW="true"
+  fi
+fi
+
+if [ "$FORCE_AUTOBREW" = "true" ]; then
   ARROW_USE_PKG_CONFIG="false"
 fi
 
@@ -99,7 +103,7 @@ else
         if [ -f "autobrew" ]; then
           echo "**** Using local manifest for ${PKG_BREW_NAME}"
         else
-          curl -sfL "https://jeroen.github.io/autobrew/$PKG_BREW_NAME" > autobrew
+          curl -sfL "https://autobrew.github.io/scripts/$PKG_BREW_NAME" > autobrew
           if [ $? -ne 0 ]; then
             echo "Failed to download manifest for ${PKG_BREW_NAME}"
           fi
@@ -110,7 +114,7 @@ else
         fi
       fi
       PKG_CFLAGS="-I$BREWDIR/opt/$PKG_BREW_NAME/include"
-      PKG_LIBS="-L$BREWDIR/opt/$PKG_BREW_NAME/lib $PKG_LIBS"
+      PKG_LIBS="-L$BREWDIR/opt/$PKG_BREW_NAME/lib $PKG_LIBS -larrow_bundled_dependencies"
     elif [ "$UNAME" = "Linux" ]; then
       # Set some default values/backwards compatibility
       if [ "${LIBARROW_DOWNLOAD}" = "" ] && [ "${NOT_CRAN}" != "" ]; then
@@ -127,11 +131,21 @@ else
       fi
       ${R_HOME}/bin/Rscript tools/linuxlibs.R $VERSION
       PKG_CFLAGS="-I$(pwd)/libarrow/arrow-${VERSION}/include $PKG_CFLAGS"
-      # Also enumerate the static libs (technically repeating arrow libs so they're in the right order)
-      # TODO: there must be a better way; also what about non-bundled deps?
-      BUNDLED_LIBS=`cd libarrow/arrow-${VERSION}/lib && ls *.a`
-      BUNDLED_LIBS=`echo $BUNDLED_LIBS | sed -E "s/lib(.*)\.a/-l\1/" | sed -e "s/\\.a lib/ -l/g"`
-      PKG_LIBS="-L$(pwd)/libarrow/arrow-${VERSION}/lib $PKG_LIBS $BUNDLED_LIBS"
+
+      LIB_DIR="libarrow/arrow-${VERSION}/lib"
+      if [ -d "$LIB_DIR" ]; then
+        # Enumerate the static libs and add to PKG_LIBS
+        # (technically repeating arrow libs so they're in the right order)
+        #
+        # If tools/linuxlibs.R fails to produce libs, this dir won't exist
+        # so don't try (the error message from `ls` would be misleading)
+        # Assume linuxlibs.R has handled and messaged about its failure already
+        #
+        # TODO: what about non-bundled deps?
+        BUNDLED_LIBS=`cd $LIB_DIR && ls *.a`
+        BUNDLED_LIBS=`echo $BUNDLED_LIBS | sed -E "s/lib(.*)\.a/-l\1/" | sed -e "s/\\.a lib/ -l/g"`
+        PKG_LIBS="-L$(pwd)/$LIB_DIR $PKG_LIBS $BUNDLED_LIBS"
+      fi
     fi
   fi
 fi
@@ -159,6 +173,12 @@ echo "#include $PKG_TEST_HEADER" | ${TEST_CMD} >/dev/null 2>&1
 if [ $? -eq 0 ] || [ "$UNAME" = "Darwin" ]; then
   # Always build with arrow on macOS
   PKG_CFLAGS="$PKG_CFLAGS -DARROW_R_WITH_ARROW"
+  # Check for features
+  LIB_DIR=`echo $PKG_LIBS | sed -e 's/ -l.*//' | sed -e 's/^-L//'`
+  grep 'set(ARROW_S3 "ON")' $LIB_DIR/cmake/arrow/ArrowOptions.cmake >/dev/null 2>&1
+  if [ $? -eq 0 ]; then
+    PKG_CFLAGS="$PKG_CFLAGS -DARROW_R_WITH_S3"
+  fi
   echo "PKG_CFLAGS=$PKG_CFLAGS"
   echo "PKG_LIBS=$PKG_LIBS"
 else
@@ -177,6 +197,17 @@ fi
 
 # Write to Makevars
 sed -e "s|@cflags@|$PKG_CFLAGS|" -e "s|@libs@|$PKG_LIBS|" src/Makevars.in > src/Makevars
+
+# # Add stripping
+# if [ "$R_STRIP_SHARED_LIB" != "" ]; then
+#   # R_STRIP_SHARED_LIB is set in the global Renviron and should be available here
+#   echo "
+# strip: \$(SHLIB)
+# 	$R_STRIP_SHARED_LIB \$(SHLIB) >/dev/null 2>&1 || true
+#
+# .phony: strip
+# " >> src/Makevars
+# fi
 
 # Success
 exit 0
